id: funneldrop_analyze_data
title: We're losing users
description: We need your help identifying the cause of a massive drop in one of our
  funnels.
hints:
- Try to find what all the users that drop in the funnel have in common
startBot: head-of-rd
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: We've identified something very worrying on our website, and this time
          it’s not a racoon!
        delay: 700
      - text: Here’s a data dump of our **analytics with the recent traffic** and
          churned users. There seem to be **too many of them**, as we both know that
          the website is perfect. So **this must be a bug of some sort**. \nhttps://drive.google.com/file/d/1ax-K7cpTp24fDZaNZNRINX3FJT6BiDv6/view
        delay: 2500
      - text: Please find out what’s happening and let me know here **what type of
          users we’re losing**.
        delay: 3500
isGeneric: true
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - mobile
          - - non web
          - - android
            - ios
          - - android
            - iphone
          - - android
            - mobile
          - - iphone
            - mobile
          - - ios
            - mobile
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Good catch! I'll let the support team know.
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Try again! I'm sure you'll figure this out.
              delay: 2500
