id: funneldrop_analyze_data
learningObjectives:
- Analyzing log data 
hints:
- Try to find what all the users that drop in the funnel have in common.
- The ’**follow_success**’ column in the dump file shows whether the user successfully followed another user or not.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "So, We've identified a very concerning **drop in a flow where users follow other users**. Here’s a data dump of our analytics with the recent traffic, including a flag ’**follow_success**’ for whether the user successfully followed another user or not."
        delay: 3000
      - text: "Please take a look and see if you can identify the problem and fix it. [You can find the dump here](https://drive.google.com/file/d/1ax-K7cpTp24fDZaNZNRINX3FJT6BiDv6/view)."
        delay: 2000
      - text: "Once you’ve found it, please drop me a message here and :instruction[let me know what type of users are not following anybody else] - so we'll be able to understand the impact and start working on a solution."
        delay: 3500
trigger:
  type: user_message
  params:
    person: head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - mobile
          - - non web
          - - android
            - ios
          - - android
            - iphone
          - - android
            - mobile
          - - iphone
            - mobile
          - - ios
            - mobile
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Good catch! Seems like our website is not entirely mobile-friendly... I'll let the support team know.
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Try again! I'm sure you'll figure this out.
              delay: 2500
solution:
  do:
    - actionId: bot_message
      params:
        messages:
          - text: Looking at the `user_agent` for users with `follow_success=FALSE`, it seems like these are all mobile devices.
          - text: Yep, so the type of users who we aren't accounting for are those on :instruction[mobile].
