id: funneldrop_reproduce_locally
learningObjectives:
- Reproducing a bug locally
hints:
- All modern web browsers can show you what your website looks like on mobile, so
  you'll be able to easily debug and develop for mobile. You can use the developer
  tools to see it.
- This is probably the url of the page where users can choose to follow other users.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "Now that we know which users are unable to follow other users, we can start fixing the bug."      
        delay: 1300
      - text: "Let's begin by :instruction[reproducing the bug in your dev environment]."
        delat: 1000
      - text:  "After reproduced, :instruction[send me the URL of the path] where you saw the issue. Then we’ll try to fix it in your dev environment, and only if it works, we’ll fix it in production."
        delay: 1200
trigger:
  type: user_message
  params:
    person: head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: '\/@[a-zA-Z0-9_-]+'
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: "Wow, that is indeed a problematic screen! Looks like we forgot about mobile devices when we created this screen."
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: "Umm, that doesn't look right. Maybe it's a different URL?"
              delay: 1400
solution:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: The page where users can choose to follow other users is the user profile page.
          - text: It should be something like :instruction[/@username].
